### PR TITLE
add file

### PR DESCRIPTION
**Pull request by zefantoo**

### CODE REVIEW

**Comment by PetrovDw** [comment]
Hi @zefantoo. Is 0x7796cb93a7ba842da2acd5fedd47fcf47b64e244 your node address? I can't find it in the list of registered validators.

**Comment by zefantoo** [comment]
Where should I find the correct node address?

**Comment by zefantoo** [comment]
> Hi @zefantoo. Is 0x7796cb93a7ba842da2acd5fedd47fcf47b64e244 your node address? I can't find it in the list of registered validators.

**Comment by zefantoo** [comment]
> 你好@zefantoo。0x7796cb93a7ba842da2acd5fedd47fcf47b64e244是你的节点地址吗？我在注册验证者列表中找不到它。

Where should I find the correct node address?

**Comment by zefantoo** [comment]
The verification of the node registration has been completed, and the address in the node list is this one. Please double-check and confirm the merge. Thank you.

**Pull request closed without merging**
