### PR TITLE
autonity validator

### PR DESCRIPTION
**Pull request by TonyStarkMan2**

### CODE REVIEW

**Comment by i7495** [comment]
Hi @TonyStarkMan2.

Please check the [instruction](https://github.com/stakeflow/network-registry/blob/main/TUTORIAL.md). Your files should be named `logo.png` and `validator-details.json`.

**Comment by TonyStarkMan2** [comment]
renamed

**Comment by i7495** [comment]
@TonyStarkMan2 
There are two more issues that need to be fixed:

1) Your validator-details.json has a syntax error due to a missing comma after the “website” field. Please correct it as shown below:
`"website": ""` -> `"website": "",`

2) Fix the location of your files in repo. Your files should be placed in a folder named according to your validator address.

**Comment by i7495** [comment]
The path should include the chain (in your case it is Autonity Piccadilly testnet). You need to place your files in `autonity-piccadilly-testnet/validators/0xd88c0fa97028721b827846df554f317bfaa0e13a`, not in `0xd88c0fa97028721b827846df554f317bfaa0e13a`.

Here you can check examples from other validators: https://github.com/stakeflow/network-registry/tree/main/autonity-piccadilly-testnet/validators

**Pull request merged**
