### PR TITLE
Add WellNode info

### PR DESCRIPTION
**Pull request by yarnik1**

### CODE REVIEW

**Comment by i7495** [comment]
Hi @yarnik1. There are some issues with the pull request:
1. You need to use `.png` or `.svg` for your logo image
2. You need to name it exactly `logo.png` or `logo.svg`

It is required since our explorer can't fetch logo files with names other than `logo.png` or `logo.svg`

**Comment by yarnik1** [comment]
new avatar

**Comment by i7495** [comment]
@yarnik1 one more thing to fix: the name of the logo file should be `logo.png` and not `WellNOde.png`. So please rename the file from `WellNOde.png` to `logo.png`.

**Comment by yarnik1** [comment]
Done

**Pull request merged**
